name: "Cache projectcreatedc.org"
on:
  schedule:
  - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Homepage
        run: curl "https://projectcreatedc.org"
      - name: Cache News Page
        run: curl "https://projectcreatedc.org/news-events/news/"
      - name: Cache Staff Page
        run: curl "https://projectcreatedc.org/about-us/our-people/our-staff/"
      - name: Cache Teachers Page
        run: curl "https://projectcreatedc.org/about-us/our-people/teachers-therapists/"