name: "Cache projectcreatedc.org"
on:
  schedule:
  - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Homepage
        run: curl "projectcreatedc.org"